'use client';
import React, { useCallback, useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import EditIcon from '@/components/icons/EditIcon';
import DeleteIcon from '@/components/icons/DeleteIcon';
import { makeApiCall } from '@/lib/apicaller';
import { StudentService } from '@/services/api/students-service';
import EditPopup from './EditPopup';
import { ToastVariant, toastWithTimeout } from '@/components/ui/use-toast';
import QRCode from 'qrcode';
import { UserService } from '@/services/api/user-service';
import { toPng, toJpeg, toSvg } from 'html-to-image';
import html2canvas from 'html2canvas';

export default function EquipmentTable({ data, setChanged, changed }: { data: any, setChanged: any, changed: boolean }) {
    const [editingRow, setEditingRow] = useState<any>(null);




    const handleEditClick = (slNo: number) => {
        setEditingRow(slNo === editingRow ? null : slNo!);
    };

    const handleCloseEdit = () => {
        setEditingRow(null);
    };
    async function loadImages(element: any) {
        const images = element.getElementsByTagName('img');
        const promises = [];

        for (let img of images) {
            if (!img.complete) {
                promises.push(
                    new Promise((resolve, reject) => {
                        img.onload = resolve;
                        img.onerror = reject;
                    })
                );
            }
        }

        await Promise.all(promises);
    }

    const generateQr = async (item:any) => {
        try {
           
            // Create an HTML template for the card
            const htmlElement = document.createElement('div');
            htmlElement.innerHTML = await fetchHtml(item);

            // Append the element to the body temporarily
            document.body.appendChild(htmlElement);
            await loadImages(htmlElement);

            console.log(htmlElement.outerHTML);

            // Convert the HTML element to a PNG image
            const dataUrl = await toPng(htmlElement, {
                quality: 0.95,
                width: htmlElement.offsetWidth,
                height: htmlElement.offsetHeight,
            });

            // Remove the temporary element
            document.body.removeChild(htmlElement);

            // Convert Data URL to Blob
            const imageBlob = dataURLtoBlob(dataUrl);

            // Upload the card image and get its URL
            const cardImageUrl = await uploadImage(imageBlob);

            if (cardImageUrl) {
                // Update the student's card_url in the database
                await makeApiCall(
                    () => new StudentService().updateStudentCardUrl(item?.id, cardImageUrl),
                    {
                        afterSuccess: (data: any) => {
                            console.log('Card image URL updated:', data);
                        },
                    }
                );

                // Now generate a QR code that points to the card image URL
                const qrDataUrl = await QRCode.toDataURL(cardImageUrl, {
                    width: 300,
                    errorCorrectionLevel: 'H',
                });

                // Convert QR code Data URL to Blob
                const qrImageBlob = dataURLtoBlob(qrDataUrl);

                // Upload the QR code image and get its URL
                const qrImageUrl = await uploadImage(qrImageBlob);

                if (qrImageUrl) {
                    // Update the student's card_qr_url in the database
                    await makeApiCall(
                        () => new StudentService().updateStudentQRUrl(item?.id, qrImageUrl),
                        {
                            afterSuccess: (data: any) => {
                                console.log('QR code image URL updated:', data);
                            },
                        }
                    );

                    setChanged(!changed);
                    toastWithTimeout(ToastVariant.Success, "Card and QR code created successfully.");
                } else {
                    toastWithTimeout(ToastVariant.Error, "Failed to upload QR image.");
                }
            } else {
                toastWithTimeout(ToastVariant.Error, "Failed to upload card image.");
            }
        } catch (error) {
            console.error("Error generating QR code:", error);
            toastWithTimeout(ToastVariant.Error, "An error occurred while generating the QR code.");
        }
    };

    const fetchHtml = async (item:any) => {
        const htmlString = `
        <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Generated by Codia AI</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" />
<style>
:root {
--default-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
Ubuntu, "Helvetica Neue", Helvetica, Arial, "PingFang SC",
"Hiragino Sans GB", "Microsoft Yahei UI", "Microsoft Yahei",
"Source Han Sans CN", sans-serif;
}

.main-container {
overflow: hidden;
}

.main-container,
.main-container * {
box-sizing: border-box;
}

input,
select,
textarea,
button {
outline: 0;
}

.main-container {
position: relative;
width: 595px;
height: 842px;
margin: 0 auto;
background: #ffffff;
overflow: hidden;
}
.rectangle {
position: absolute;
width: 43.224px;
height: 883.813px;
top: -16.328px;
left: 0;
background: #8d1b3d;
z-index: 11;
}
.whatsapp-image {
position: absolute;
width: 178.444px;
height: 50.344px;
top: 78.535px;
left: 67.5px;
background: url(/blank_certificate/images/8c6dea95de03a5cdcee3820f6ffcd969fa994d12.png)
no-repeat center;
background-size: cover;
z-index: 10;
}
.qr-code-verification-report {
position: absolute;
width: 514.973px;
height: 34px;
top: 155.484px;
left: 71.944px;
font-family: Inter, var(--default-font-family);
font-size: 16px;
font-weight: 400;
line-height: 22px;
text-align: left;
letter-spacing: -0.64px;
z-index: 4;
}
.qr-code-verification-report-1 {
position: relative;
color: #171717;
font-family: Inter, var(--default-font-family);
font-size: 16px;
font-weight: 700;
line-height: 22px;
text-align: left;
letter-spacing: -0.64px;
}
.qr-code-authenticated-results {
position: relative;
color: #171717;
font-family: Inter, var(--default-font-family);
font-size: 16px;
font-weight: 400;
line-height: 22px;
text-align: left;
letter-spacing: -0.64px;
}
.profile-photo {
position: absolute;
width: 17.31%;
height: 13.06%;
top: 27.34%;
left: 12.09%;
background: url(${item?.avatar})
no-repeat center;
background-size: cover;
z-index: 9;
border-radius: 15px;
}
.sheik-hameed-khan {
display: flex;
align-items: flex-start;
justify-content: flex-start;
position: absolute;
height: 3.09%;
top: 43.57%;
left: 12.09%;
color: #171717;
font-family: Inter, var(--default-font-family);
font-size: 24px;
font-weight: 600;
line-height: 26px;
text-align: center;
white-space: nowrap;
z-index: 8;
}
.nome {
display: flex;
align-items: flex-start;
flex-wrap: nowrap;
gap: 15.485px;
position: absolute;
width: 174px;
height: 157px;
top: 50%;
left: 50%;
transform: translate(-129.63%, -7.14%);
}
.apparicio-junior {
display: flex;
align-items: flex-start;
justify-content: flex-start;
flex-shrink: 0;
position: relative;
width: 174px;
height: 157px;
color: #171717;
font-family: Inter, var(--default-font-family);
font-size: 20px;
font-weight: 500;
line-height: 71.233px;
text-align: left;
text-overflow: initial;
letter-spacing: -0.8px;
z-index: 1;
overflow: hidden;
}
.qube-inspection-basic {
display: flex;
align-items: flex-start;
justify-content: flex-start;
position: absolute;
width: 201.257px;
height: 132px;
top: 468.398px;
left: 259.973px;
color: #171717;
font-family: Inter, var(--default-font-family);
font-size: 16px;
font-weight: 400;
line-height: 30px;
text-align: left;
letter-spacing: -0.64px;
z-index: 3;
}
.qatar-id-company {
display: flex;
align-items: flex-start;
justify-content: flex-start;
position: absolute;
width: 163.029px;
height: 132px;
top: calc(50% - -47.4px);
left: calc(50% - 225.56px);
color: rgba(0, 0, 0, 0.5);
font-family: Inter, var(--default-font-family);
font-size: 16px;
font-weight: 400;
line-height: 30px;
text-align: left;
letter-spacing: -0.64px;
z-index: 2;
}
.line {
position: absolute;
width: 62.71%;
height: 0.18%;
top: 70.29%;
left: 12.09%;
background: url(/blank_certificate/images/ed1ac0da-e9fe-4b76-b073-cc9e922ba016.png)
no-repeat center;
background-size: 100% 100%;
z-index: 5;
}
.issued-expiry {
display: flex;
align-items: flex-start;
justify-content: flex-start;
position: absolute;
height: 5.23%;
top: 75.55%;
left: 12.09%;
color: rgba(0, 0, 0, 0.5);
font-family: Inter, var(--default-font-family);
font-size: 16px;
font-weight: 400;
line-height: 32px;
text-align: left;
white-space: nowrap;
letter-spacing: -0.64px;
z-index: 6;
}
.date {
display: flex;
align-items: flex-start;
justify-content: flex-start;
position: absolute;
height: 5.23%;
top: 75.55%;
left: 43.69%;
color: #171717;
font-family: Inter, var(--default-font-family);
font-size: 16px;
font-weight: 400;
line-height: 32px;
text-align: left;
white-space: nowrap;
letter-spacing: -0.64px;
z-index: 7;
}
.contact-info {
display: flex;
align-items: flex-start;
justify-content: flex-end;
position: absolute;
width: 104.24%;
height: 2.02%;
top: 95.93%;
left: -8.43%;
color: #8d1b3d;
font-family: Inter, var(--default-font-family);
font-size: 12px;
font-weight: 500;
line-height: 17px;
text-align: right;
white-space: nowrap;
letter-spacing: 0.24px;
z-index: 12;
}

</style>
</head>
<body>
<div class="main-container">
<div class="rectangle"></div>
<div class="whatsapp-image"></div>
<div class="qr-code-verification-report">
<span class="qr-code-verification-report-1"
  >QR Code Verification Report<br /></span
><span class="qr-code-authenticated-results"
  >This QR code is authenticated and the results are as below</span
>
</div>
<div class="profile-photo"></div>
<span class="sheik-hameed-khan">${item?.name}</span>
<div class="nome">
<span class="apparicio-junior">${item?.certificate_no}<br /><br /></span>
</div>
<span class="qube-inspection-basic"
>${item?.id_no}<br />${item?.company}<br />${item?.designation}<br />${item?.model_level}<br />${item?.course_duration+" " || 2+" "}day</span
><span class="qatar-id-company"
>Qatar ID/ ID No.: <br />Company name:<br />Designation:<br />Model/
Level:<br />Course Duration:</span
>
<div class="line"></div>
<span class="issued-expiry">Issued Date: <br />Expiry Date:</span
><span class="date">${item?.issued_on}<br />${item?.valid_untill}</span
><span class="contact-info"
>+974 31499334 | Info@qubeinspection.com | www.qubeinspection.com</span
>
</div>
<!-- Generated by Codia AI - https://codia.ai/ -->
</body>
</html>

        `
        console.log(htmlString, "htmlString");
        
        return htmlString;
    };

    const dataURLtoBlob = (dataUrl: string) => {
        const arr = dataUrl.split(',');
        const mimeMatch = arr[0].match(/:(.*?);/);
        const mime = mimeMatch ? mimeMatch[1] : '';
        const bstr = atob(arr[1]);
        let n = bstr.length;
        const u8arr = new Uint8Array(n);

        while (n--) {
            u8arr[n] = bstr.charCodeAt(n);
        }

        return new Blob([u8arr], { type: mime });
    };

    const uploadImage = async (imageBlob: string | Blob) => {
        if (!imageBlob) return null;

        const formData = new FormData();
        formData.append('file', imageBlob);

        try {
            let res: any;
            const result = await makeApiCall(
                () => new UserService().uploadFile(formData, `${Date.now()}`, 'students'),
                {
                    afterSuccess: (data: any) => {
                        res = data
                    },
                }
            );
            console.log(res, "data is sreerag");

            return res?.fullPath
                ? `https://seqptsvnihezsfbnpkpz.supabase.co/storage/v1/object/public/${res.fullPath}`
                : null;
        } catch (error) {
            console.error("Error uploading image:", error);
            return null;
        }
    };

    return (
        <div className="px-8 py-3 bg-white w-[98%] mx-auto">
            <Table className="w-full">
                <TableHeader>
                    <TableRow>
                        <TableHead className="py-4">ID</TableHead>
                        <TableHead className="py-4">Name</TableHead>
                        <TableHead className="py-4">Added_By</TableHead>
                        <TableHead className="py-4">Image</TableHead>
                        <TableHead className="py-4">Card/Model Level</TableHead>
                        <TableHead className="py-4  px-2 ">QR Image</TableHead>
                        <TableHead className="py-4">Action</TableHead>
                    </TableRow>
                </TableHeader>
                <TableBody>
                    {data?.map((item: any, idx: number) => (
                        <React.Fragment key={idx + 1}>
                            <TableRow>
                                <TableCell className="py-4">{item.id}</TableCell>
                                <TableCell className="py-4">
                                    {item.name}
                                    <div>Address: {item.address}</div>
                                    <div>Designation: {item.designation}</div>
                                </TableCell>
                                <TableCell className="py-4">{item.added_by}</TableCell>
                                <TableCell className="py-4">
                                    <img src={item.avatar} alt="profile" className="w-16 h-16 rounded-full" />
                                </TableCell>
                                <TableCell className="py-4">
                                    <div>ID No: {item.id_number}</div>
                                    <div>Card No: {item.card_number}</div>
                                    <div>Model/Level: {item.model_level}</div>
                                    <div>Company: {item.company}</div>
                                </TableCell>
                                <TableCell className="py-4">
                                    {item.qr_url ? (
                                        <img src={item.qr_url} alt="QR code" className="w-16 h-16" />
                                    ) : (
                                        <button
                                            onClick={() => generateQr(item)}
                                            className="bg-white p-1 px-2 flex rounded-md w-[78%] border-primary border text-primary"
                                        >
                                            Generate QR
                                        </button>
                                    )}
                                </TableCell>
                                <TableCell className="py-4">
                                    <div className="flex space-x-2">
                                        <button onClick={() => handleEditClick(idx + 1)} className="text-red-500">
                                            <EditIcon />
                                        </button>
                                        <button className="text-red-500">
                                            <DeleteIcon />
                                        </button>
                                    </div>
                                </TableCell>
                            </TableRow>
                            <AnimatePresence>
                                {editingRow === idx + 1 && (
                                    <motion.tr
                                        initial={{ opacity: 0, height: 0 }}
                                        animate={{ opacity: 1, height: 'auto' }}
                                        exit={{ opacity: 0, height: 0 }}
                                        transition={{ duration: 0.2 }}
                                    >
                                        <TableCell colSpan={7}>
                                            <div className="overflow-hidden">
                                                <EditPopup onClose={handleCloseEdit} id={Number(item.id)} />
                                            </div>
                                        </TableCell>
                                    </motion.tr>
                                )}
                            </AnimatePresence>
                        </React.Fragment>
                    ))}
                </TableBody>
            </Table>
        </div>
    );
}
